apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: "{{ .Values.applicationName }}-docker-registry-secret"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  .dockerconfigjson: {{ printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registry.url (printf "%s:%s" (required "Missing 'registry.username'!" .Values.registry.username) (required "Missing 'registry.password'!" .Values.registry.password) | b64enc) | b64enc }}
